version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        ports:
            - "8080:80"
        environment:
            - DB_HOST=db
        depends_on:
            - db
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: laravel
            MYSQL_USER: usuario
            MYSQL_PASSWORD: 1234
        ports:
            - "3306:3306"
volumes:
    db_data:
